baseURL: "https://waugh.zip/"
title: Lachlan Waugh
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 5

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Lachlan Waugh
  description: "Security Engineer"
  keywords: [Blog, Portfolio, PaperMod]
  author: melon
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Lachlan Waugh"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Lachlan
    subtitle: "Security Engineer"
    imageUrl: "melon.webp"
    imageWidth: 180
    imageHeight: 180
    imageTitle: a picture of a watermelon (yum)
    buttons:
    - name: resume
      url: /resume.pdf

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/lachlan-waugh"
    - name: email
      url: "mailto:lachlan@waugh.zip"
    - name: twitter
      url: "https://twitter.com/lcahaln"
    - name: linkedin
      url: "https://linkedin.com/in/lachlan-waugh"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 20
    - identifier: experience
      name: experience
      url: /experience/
      weight: 30
    - identifier: tutoring
      name: tutoring
      url: /tutoring/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
